"use client";

import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { 
    Search, Filter, BookOpen, Clock, 
    ArrowRight, Trophy, Zap, 
    Layers, BrainCircuit, Target,
    CheckCircle2, ChevronRight
} from "lucide-react";
import Link from "next/link";
import { motion, AnimatePresence } from "framer-motion";
import { useRouter } from "next/navigation";

export default function AssessmentExplorer() {
    const supabase = createClient();
    const router = useRouter();
    const [assessments, setAssessments] = useState<any[]>([]);
    const [loading, setLoading] = useState(true);
    const [isGenerating, setIsGenerating] = useState(false);
    const [searchQuery, setSearchQuery] = useState("");
    const [quickSkill, setQuickSkill] = useState("");
    const [activeCategory, setActiveCategory] = useState("all");

    useEffect(() => {
        const fetchAssessments = async () => {
            const { data } = await supabase
                .from("assessments")
                .select(`
                    *,
                    creator:profiles!creator_id(full_name, avatar_url)
                `)
                .eq("is_active", true)
                .order("created_at", { ascending: false });

            if (data) setAssessments(data);
            setLoading(false);
        };

        fetchAssessments();
    }, [supabase]);

    const categories = ["all", "technical", "behavioral", "design", "management", "systems"];
    
    const filtered = assessments.filter(a => {
        const matchesSearch = a.title.toLowerCase().includes(searchQuery.toLowerCase());
        const matchesCategory = activeCategory === "all" || a.category === activeCategory;
        return matchesSearch && matchesCategory;
    });

    const handleQuickVetting = async () => {
        if (!quickSkill) return;

        const { data: { user } } = await supabase.auth.getUser();
        if (!user) return;

        setIsGenerating(true);
        try {
            const response = await fetch("/api/assessments/generate", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ skill: quickSkill, count: 5 })
            });

            if (!response.ok) throw new Error("Neural generation failed.");
            const data = await response.json();

            // Create temporary assessment
            const { data: assessment, error } = await supabase
                .from("assessments")
                .insert({
                    title: `Neural Vetting: ${quickSkill}`,
                    description: `Automated technical vetting mission for ${quickSkill}. Verification node generated by HireSight AI.`,
                    category: activeCategory === "all" ? "technical" : activeCategory,
                    duration_minutes: 10,
                    passing_score: 70,
                    creator_id: user.id,
                    is_active: false // Private to this user's session initially
                })
                .select()
                .single();

            if (error || !assessment) throw error;

            // Save questions
            const questions = data.questions.map((q: any, idx: number) => ({
                assessment_id: assessment.id,
                question_text: q.text,
                options: q.options,
                correct_answer: q.correctAnswer.toString(),
                explanation: q.explanation || "",
                points: q.points || 1,
                order_index: idx
            }));

            await supabase.from("assessment_questions").insert(questions);

            // Redirect to take
            router.push(`/dashboard/assessments/${assessment.id}/take`);
        } catch (error: any) {
            alert(`Neural Sync Error: ${error.message}`);
        } finally {
            setIsGenerating(false);
        }
    };

    if (loading) return (
        <div className="flex items-center justify-center min-h-[400px]">
             <div className="w-10 h-10 border-4 border-primary border-t-transparent rounded-full animate-spin" />
        </div>
    );

    return (
        <div className="max-w-7xl mx-auto space-y-12 pb-32">
            {/* Header */}
            <header className="flex flex-col md:flex-row md:items-end md:justify-between gap-8">
                <div className="space-y-4">
                    <div className="flex items-center space-x-3 text-primary">
                         <BrainCircuit className="w-6 h-6" />
                         <span className="text-[10px] font-black uppercase tracking-[0.2em] italic underline decoration-2 decoration-primary/20">Skill Discovery Hub</span>
                    </div>
                    <h1 className="text-4xl md:text-6xl font-black font-display text-zinc-900 italic tracking-tighter">
                        Vetting <span className="text-primary tracking-normal">Explorer</span>
                    </h1>
                    <p className="text-gray-500 font-bold max-w-lg">Initiate a neural vetting cycle to verify your technical profile and earn verifiable skill badges.</p>
                </div>

                <div className="flex items-center space-x-4 bg-gray-50 p-2 rounded-[32px] border border-gray-100">
                     <Link href="/dashboard/achievements" className="px-6 py-3 bg-white text-zinc-900 rounded-[24px] font-black text-[10px] uppercase tracking-widest italic shadow-sm hover:scale-105 transition-all flex items-center space-x-2">
                        <Trophy className="w-4 h-4 text-primary" />
                        <span>Trophy Case</span>
                     </Link>
                </div>
            </header>

            {/* Quick Vetting Bar */}
            <div className="bg-zinc-900 rounded-[48px] p-8 md:p-12 shadow-2xl relative overflow-hidden group">
                 <div className="relative z-10 flex flex-col lg:flex-row items-center justify-between gap-8">
                     <div className="space-y-2 text-center lg:text-left">
                        <h2 className="text-2xl md:text-3xl font-black text-white italic tracking-tighter">Instant <span className="text-primary italic">Neural Vetting</span></h2>
                        <p className="text-white/40 text-xs font-bold uppercase tracking-widest italic">Generate a custom verification mission for any skill node</p>
                     </div>
                     <div className="flex flex-col sm:flex-row items-center gap-4 w-full lg:w-auto">
                        <div className="relative flex-1 sm:w-80 group/input">
                            <BrainCircuit className="absolute left-6 top-1/2 -translate-y-1/2 w-5 h-5 text-white/20 group-focus-within/input:text-primary transition-colors" />
                            <input 
                                type="text"
                                placeholder="Enter skill (e.g. React, Docker...)"
                                value={quickSkill}
                                onChange={(e) => setQuickSkill(e.target.value)}
                                className="w-full pl-14 pr-6 py-4 bg-white/5 border border-white/10 rounded-2xl text-white font-bold focus:outline-none focus:border-primary/50 transition-all placeholder:text-white/20"
                            />
                        </div>
                        <button 
                            onClick={handleQuickVetting}
                            disabled={isGenerating || !quickSkill}
                            className="w-full sm:w-auto px-10 py-5 bg-primary text-white rounded-[24px] font-black text-[10px] uppercase tracking-[0.2em] italic hover:scale-105 transition-all shadow-xl shadow-primary/20 disabled:opacity-50 disabled:grayscale flex items-center justify-center space-x-3"
                        >
                            {isGenerating ? (
                                <>
                                    <div className="w-4 h-4 border-2 border-white/20 border-t-white rounded-full animate-spin" />
                                    <span>Generating Node...</span>
                                </>
                            ) : (
                                <>
                                    <span>Launch Mission</span>
                                    <Target className="w-4 h-4" />
                                </>
                            )}
                        </button>
                     </div>
                 </div>
                 <div className="absolute right-0 top-0 w-64 h-full bg-primary/10 -skew-x-12 translate-x-20 pointer-events-none group-hover:bg-primary/20 transition-all" />
            </div>

            {/* Filter Bar */}
            <div className="flex flex-col lg:flex-row gap-6 items-center">
                <div className="relative flex-1 group w-full">
                    <Search className="absolute left-8 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400 group-focus-within:text-primary transition-colors" />
                    <input 
                        type="text"
                        placeholder="Search technical blueprints (e.g. Python, React, Systems Architecture)..."
                        value={searchQuery}
                        onChange={(e) => setSearchQuery(e.target.value)}
                        className="w-full pl-20 pr-8 py-6 bg-white border border-gray-100 rounded-[32px] text-sm font-bold focus:outline-none focus:ring-4 focus:ring-primary/5 transition-all shadow-sm"
                    />
                </div>
                <div className="flex flex-wrap items-center gap-3">
                    {categories.map(cat => (
                        <button
                            key={cat}
                            onClick={() => setActiveCategory(cat)}
                            className={`px-6 py-3 rounded-2xl text-[10px] font-black uppercase tracking-widest transition-all ${
                                activeCategory === cat 
                                ? "bg-zinc-900 text-white shadow-xl" 
                                : "bg-white border border-gray-100 text-gray-400 hover:bg-gray-50"
                            }`}
                        >
                            {cat}
                        </button>
                    ))}
                </div>
            </div>

            {/* Assessment Grid */}
            {filtered.length > 0 ? (
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                    {filtered.map((a) => (
                        <AssessmentCard key={a.id} assessment={a} />
                    ))}
                </div>
            ) : (
                <div className="bg-white border-2 border-dashed border-gray-100 rounded-[56px] p-24 text-center space-y-8">
                    <div className="w-24 h-24 bg-gray-50 rounded-full flex items-center justify-center mx-auto text-gray-300">
                        <Layers className="w-12 h-12" />
                    </div>
                    <div className="space-y-4">
                        <h3 className="text-3xl font-black text-zinc-900 italic tracking-tight uppercase">Blueprints Not Found</h3>
                        <p className="text-gray-500 font-bold max-w-sm mx-auto italic">Our neural models haven't indexed any assessments matching your parameters. Check back shortly for updated missions.</p>
                    </div>
                </div>
            )}
        </div>
    );
}

function AssessmentCard({ assessment }: { assessment: any }) {
    return (
        <motion.div 
            whileHover={{ y: -10 }}
            className="group bg-white border border-gray-100 rounded-[48px] p-8 hover:shadow-2xl hover:border-primary/20 transition-all flex flex-col justify-between h-[420px] relative overflow-hidden shadow-sm"
        >
            <div className="relative z-10 space-y-6">
                <div className="flex justify-between items-start">
                    <div className="p-4 bg-primary/5 text-primary rounded-[24px]">
                        < Zap className="w-6 h-6" />
                    </div>
                    <span className="px-3 py-1 bg-gray-900 text-white text-[8px] font-black uppercase tracking-widest rounded-lg italic">{assessment.category}</span>
                </div>

                <div className="space-y-2">
                    <h3 className="text-2xl font-black text-zinc-900 italic tracking-tighter leading-tight group-hover:text-primary transition-colors">{assessment.title}</h3>
                    <p className="text-gray-400 text-xs font-bold line-clamp-2 italic">{assessment.description || "Deploy technical resources to verify your competency in this neural node."}</p>
                </div>

                <div className="grid grid-cols-2 gap-4">
                    <div className="p-4 bg-gray-50 rounded-2xl space-y-1">
                        <p className="text-[8px] font-black text-gray-400 uppercase tracking-widest underline decoration-primary/20">Runtime</p>
                        <p className="text-sm font-black text-zinc-900 italic">{assessment.duration_minutes}m</p>
                    </div>
                    <div className="p-4 bg-gray-50 rounded-2xl space-y-1">
                        <p className="text-[8px] font-black text-gray-400 uppercase tracking-widest underline decoration-primary/20">Standard</p>
                        <p className="text-sm font-black text-zinc-900 italic">{assessment.passing_score}%</p>
                    </div>
                </div>
            </div>

            <div className="relative z-10 pt-6 flex items-center justify-between border-t border-gray-50">
                 <div className="flex items-center space-x-2">
                      <div className="w-8 h-8 bg-primary/10 rounded-full flex items-center justify-center font-black text-[10px] text-primary italic">
                          {assessment.creator?.full_name?.[0] || "H"}
                      </div>
                      <span className="text-[9px] font-black text-gray-400 uppercase tracking-widest italic">{assessment.creator?.full_name || "HireSight Internal"}</span>
                 </div>
                 <Link 
                    href={`/dashboard/assessments/${assessment.id}/take`}
                    className="p-4 bg-zinc-900 text-white rounded-2xl hover:bg-primary transition-all shadow-xl shadow-zinc-900/10 group/btn"
                 >
                    <ArrowRight className="w-5 h-5 group-hover/btn:translate-x-1 transition-transform" />
                 </Link>
            </div>

            <div className="absolute right-0 bottom-0 w-48 h-48 bg-primary/5 blur-[80px] rounded-full translate-x-1/3 translate-y-1/3 opacity-0 group-hover:opacity-100 transition-opacity" />
        </motion.div>
    );
}
