# Generated by Django 6.0.1 on 2026-01-27 17:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='User email address (used for login)', max_length=255, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('account_type', models.CharField(choices=[('personal', 'Personal (Job Seeker)'), ('company', 'Company (Recruiter)')], default='personal', help_text='Type of account: personal (job seeker) or company (recruiter)', max_length=20)),
                ('two_factor_enabled', models.BooleanField(default=False, help_text='Whether two-factor authentication is enabled')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False, help_text='Email verification status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountDeletionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(help_text='Email of deleted account', max_length=254)),
                ('account_type', models.CharField(help_text='Account type (personal/company)', max_length=20)),
                ('deletion_reason', models.TextField(blank=True, help_text='Optional reason for deletion')),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_by_user', models.BooleanField(default=True, help_text='True if user deleted their own account')),
                ('account_age_days', models.IntegerField(blank=True, help_text='How many days the account existed', null=True)),
                ('total_applications', models.IntegerField(default=0, help_text='Number of applications made (if personal)')),
                ('total_job_posts', models.IntegerField(default=0, help_text='Number of jobs posted (if company)')),
            ],
            options={
                'verbose_name': 'Account Deletion Log',
                'verbose_name_plural': 'Account Deletion Logs',
                'db_table': 'account_deletion_logs',
                'ordering': ['-deleted_at'],
                'indexes': [models.Index(fields=['deleted_at'], name='account_del_deleted_534e28_idx'), models.Index(fields=['account_type'], name='account_del_account_31bff1_idx')],
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Descriptive name for this API key', max_length=255)),
                ('key', models.CharField(help_text='The actual API key string', max_length=64, unique=True)),
                ('key_prefix', models.CharField(help_text='First 8 characters of the key for display purposes', max_length=8)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time this key was used', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this key is currently active')),
                ('user', models.ForeignKey(help_text='User who owns this API key', on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'db_table': 'api_keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('company_size', models.CharField(blank=True, choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-500', '201-500 employees'), ('501-1000', '501-1000 employees'), ('1000+', '1000+ employees')], max_length=50)),
                ('locations', models.JSONField(blank=True, default=list, help_text='Array of location objects: [{"address": "123 Main St", "city": "SF", "state": "CA", "country": "USA", "is_hq": true, "lat": 37.7749, "lng": -122.4194}]')),
                ('website', models.URLField(blank=True, max_length=512)),
                ('linkedin', models.URLField(blank=True, max_length=512)),
                ('twitter', models.URLField(blank=True, max_length=512)),
                ('facebook', models.URLField(blank=True, max_length=512)),
                ('description', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True)),
                ('culture', models.TextField(blank=True)),
                ('benefits', models.JSONField(blank=True, default=list, help_text='Array of benefits: ["Health Insurance", "Remote Work", "401k"]')),
                ('team_photos', models.JSONField(blank=True, default=list, help_text='Array of team photo objects: [{"url": "...", "caption": "Our amazing team"}]')),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Verification'), ('verified', 'Verified')], default='unverified', max_length=50)),
                ('verification_docs', models.FileField(blank=True, help_text='Business registration or tax documents', null=True, upload_to='verification_docs/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profiles',
                'db_table': 'company_profiles',
            },
        ),
        migrations.CreateModel(
            name='EmailChangeToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('new_email', models.EmailField(help_text='The new email address to change to', max_length=254)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_change_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Change Token',
                'verbose_name_plural': 'Email Change Tokens',
                'db_table': 'email_change_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailPreferences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_frequency', models.CharField(choices=[('instant', 'Instant (real-time notifications)'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest'), ('off', 'Off (in-app only)')], default='instant', help_text='Default email notification frequency', max_length=20)),
                ('notify_new_application', models.BooleanField(default=True, help_text='New job recommendations')),
                ('notify_application_status_changed', models.BooleanField(default=True, help_text='When an application status changes')),
                ('notify_new_message', models.BooleanField(default=True, help_text='When someone sends you a message')),
                ('notify_profile_viewed', models.BooleanField(default=True, help_text='When someone views your profile')),
                ('notify_new_follower', models.BooleanField(default=True, help_text='When someone follows you')),
                ('notify_followed_company_job', models.BooleanField(default=True, help_text='New jobs from companies you follow')),
                ('notify_interview_scheduled', models.BooleanField(default=True, help_text='Interview invitations and schedule changes')),
                ('notify_job_recommendations', models.BooleanField(default=True, help_text='Weekly/daily job recommendations')),
                ('notify_new_applicant', models.BooleanField(default=True, help_text='New applications received')),
                ('notify_screening_complete', models.BooleanField(default=True, help_text='Resume screening completed')),
                ('notify_job_expiring_soon', models.BooleanField(default=True, help_text='Reminders for jobs about to expire')),
                ('notify_applicant_response', models.BooleanField(default=True, help_text='When applicants respond to messages')),
                ('notify_new_company_follower', models.BooleanField(default=True, help_text='When someone follows your company')),
                ('unsubscribe_token', models.CharField(blank=True, default=None, help_text='Token for email unsubscribe links', max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_digest_sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Preferences',
                'verbose_name_plural': 'Email Preferences',
                'db_table': 'email_preferences',
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Verification Token',
                'verbose_name_plural': 'Email Verification Tokens',
                'db_table': 'email_verification_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Reset Token',
                'verbose_name_plural': 'Password Reset Tokens',
                'db_table': 'password_reset_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('headline', models.CharField(blank=True, help_text='Professional headline (e.g., "Senior React Developer")', max_length=255)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('bio', models.TextField(blank=True, help_text='Brief professional summary')),
                ('skills', models.JSONField(blank=True, default=list, help_text='Array of skill objects: [{"skill": "React", "proficiency": "expert"}]')),
                ('experience', models.JSONField(blank=True, default=list, help_text='Array of experience objects with company, role, dates, description')),
                ('education', models.JSONField(blank=True, default=list, help_text='Array of education objects with institution, degree, field, dates')),
                ('certifications', models.JSONField(blank=True, default=list, help_text='Array of certification objects')),
                ('portfolio_links', models.JSONField(blank=True, default=list, help_text='Array of portfolio link objects: [{"type": "github", "url": "..."}]')),
                ('preferred_job_types', models.JSONField(blank=True, default=list, help_text='Array of preferred job types: ["full-time", "remote"]')),
                ('remote_preference', models.CharField(choices=[('remote', 'Fully Remote'), ('hybrid', 'Hybrid (Remote + Office)'), ('on-site', 'On-site Only'), ('no_preference', 'No Preference')], default='no_preference', help_text='Preferred work location type', max_length=50)),
                ('salary_expectation_min', models.IntegerField(blank=True, null=True)),
                ('salary_expectation_max', models.IntegerField(blank=True, null=True)),
                ('salary_currency', models.CharField(blank=True, choices=[('USD', 'USD - US Dollar'), ('EUR', 'EUR - Euro'), ('GBP', 'GBP - British Pound'), ('NGN', 'NGN - Nigerian Naira'), ('CAD', 'CAD - Canadian Dollar'), ('AUD', 'AUD - Australian Dollar'), ('JPY', 'JPY - Japanese Yen'), ('CNY', 'CNY - Chinese Yuan'), ('INR', 'INR - Indian Rupee')], default='USD', max_length=10)),
                ('availability', models.CharField(choices=[('immediate', 'Immediate'), ('2_weeks', '2 Weeks Notice'), ('1_month', '1 Month Notice'), ('not_looking', 'Not Currently Looking')], default='immediate', max_length=50)),
                ('profile_visibility', models.CharField(choices=[('public', 'Public (visible to all)'), ('verified_companies', 'Verified Companies Only'), ('private', 'Private (hidden)')], default='public', max_length=50)),
                ('resume_primary_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal Profile',
                'verbose_name_plural': 'Personal Profiles',
                'db_table': 'personal_profiles',
            },
        ),
        migrations.CreateModel(
            name='ProfileView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('viewer_ip', models.GenericIPAddressField(blank=True, help_text='IP address of anonymous viewers', null=True)),
                ('viewer_user_agent', models.TextField(blank=True, help_text='Browser/device information')),
                ('viewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile_user', models.ForeignKey(help_text='User whose profile was viewed', on_delete=django.db.models.deletion.CASCADE, related_name='profile_views_received', to=settings.AUTH_USER_MODEL)),
                ('viewer', models.ForeignKey(blank=True, help_text='User who viewed the profile (null if anonymous)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_views_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile View',
                'verbose_name_plural': 'Profile Views',
                'db_table': 'profile_views',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Your full name as it should appear on resumes', max_length=200)),
                ('professional_title', models.CharField(blank=True, help_text='Current or target job title (e.g., "Senior Software Engineer")', max_length=200)),
                ('phone', models.CharField(blank=True, help_text='Primary phone number', max_length=20)),
                ('location', models.CharField(blank=True, help_text='Location (city, region, or country)', max_length=200)),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('portfolio_url', models.URLField(blank=True, help_text='Portfolio or personal website')),
                ('github_url', models.URLField(blank=True, help_text='GitHub profile URL (for technical roles)')),
                ('practice_enabled', models.BooleanField(default=True, help_text='Allow the user to create interview practice sessions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Generic profile used for resume headers and contact info', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(help_text='Django session key', max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the session', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/device information')),
                ('location', models.CharField(blank=True, help_text='Approximate location (city, country)', max_length=255)),
                ('device_type', models.CharField(blank=True, help_text='Device type (desktop, mobile, tablet)', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(help_text='When this session expires')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'db_table': 'user_sessions',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['account_type'], name='users_account_e502f1_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_verified'], name='users_is_veri_63cd6e_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['user', 'is_active'], name='api_keys_user_id_6e7352_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['key'], name='api_keys_key_291dcc_idx'),
        ),
        migrations.AddIndex(
            model_name='companyprofile',
            index=models.Index(fields=['user'], name='company_pro_user_id_8e94d9_idx'),
        ),
        migrations.AddIndex(
            model_name='companyprofile',
            index=models.Index(fields=['verification_status'], name='company_pro_verific_9a7930_idx'),
        ),
        migrations.AddIndex(
            model_name='companyprofile',
            index=models.Index(fields=['company_name'], name='company_pro_company_43f4ac_idx'),
        ),
        migrations.AddIndex(
            model_name='emailpreferences',
            index=models.Index(fields=['user'], name='email_prefe_user_id_d6c413_idx'),
        ),
        migrations.AddIndex(
            model_name='emailpreferences',
            index=models.Index(fields=['unsubscribe_token'], name='email_prefe_unsubsc_651ba1_idx'),
        ),
        migrations.AddIndex(
            model_name='personalprofile',
            index=models.Index(fields=['user'], name='personal_pr_user_id_5011e9_idx'),
        ),
        migrations.AddIndex(
            model_name='personalprofile',
            index=models.Index(fields=['profile_visibility'], name='personal_pr_profile_3d2b3d_idx'),
        ),
        migrations.AddIndex(
            model_name='profileview',
            index=models.Index(fields=['profile_user', '-viewed_at'], name='profile_vie_profile_69fac9_idx'),
        ),
        migrations.AddIndex(
            model_name='profileview',
            index=models.Index(fields=['viewer', '-viewed_at'], name='profile_vie_viewer__cc977a_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', '-last_activity'], name='user_sessio_user_id_3a59ae_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['session_key'], name='user_sessio_session_cc84b9_idx'),
        ),
    ]
