# Generated by Django 6.0.1 on 2026-01-10 14:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='User email address (used for login)', max_length=255, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('account_type', models.CharField(choices=[('personal', 'Personal (Job Seeker)'), ('company', 'Company (Recruiter)')], default='personal', help_text='Type of account: personal (job seeker) or company (recruiter)', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False, help_text='Email verification status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('company_size', models.CharField(blank=True, choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-500', '201-500 employees'), ('501-1000', '501-1000 employees'), ('1000+', '1000+ employees')], max_length=50)),
                ('locations', models.JSONField(blank=True, default=list, help_text='Array of location objects: [{"city": "SF", "state": "CA", "country": "USA", "is_hq": true}]')),
                ('website', models.URLField(blank=True, max_length=512)),
                ('description', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True)),
                ('culture', models.TextField(blank=True)),
                ('benefits', models.JSONField(blank=True, default=list, help_text='Array of benefits: ["Health Insurance", "Remote Work", "401k"]')),
                ('team_photos', models.JSONField(blank=True, default=list, help_text='Array of team photo objects: [{"url": "...", "caption": "Our amazing team"}]')),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Verification'), ('verified', 'Verified')], default='unverified', max_length=50)),
                ('verification_docs', models.FileField(blank=True, help_text='Business registration or tax documents', null=True, upload_to='verification_docs/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profiles',
                'db_table': 'company_profiles',
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Verification Token',
                'verbose_name_plural': 'Email Verification Tokens',
                'db_table': 'email_verification_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Reset Token',
                'verbose_name_plural': 'Password Reset Tokens',
                'db_table': 'password_reset_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('headline', models.CharField(blank=True, help_text='Professional headline (e.g., "Senior React Developer")', max_length=255)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('bio', models.TextField(blank=True, help_text='Brief professional summary')),
                ('skills', models.JSONField(blank=True, default=list, help_text='Array of skill objects: [{"skill": "React", "proficiency": "expert"}]')),
                ('experience', models.JSONField(blank=True, default=list, help_text='Array of experience objects with company, role, dates, description')),
                ('education', models.JSONField(blank=True, default=list, help_text='Array of education objects with institution, degree, field, dates')),
                ('certifications', models.JSONField(blank=True, default=list, help_text='Array of certification objects')),
                ('portfolio_links', models.JSONField(blank=True, default=list, help_text='Array of portfolio link objects: [{"type": "github", "url": "..."}]')),
                ('preferred_job_types', models.JSONField(blank=True, default=list, help_text='Array of preferred job types: ["full-time", "remote"]')),
                ('salary_expectation_min', models.IntegerField(blank=True, null=True)),
                ('salary_expectation_max', models.IntegerField(blank=True, null=True)),
                ('salary_currency', models.CharField(default='USD', max_length=10)),
                ('availability', models.CharField(choices=[('immediate', 'Immediate'), ('2_weeks', '2 Weeks Notice'), ('1_month', '1 Month Notice'), ('not_looking', 'Not Currently Looking')], default='immediate', max_length=50)),
                ('profile_visibility', models.CharField(choices=[('public', 'Public (visible to all)'), ('verified_companies', 'Verified Companies Only'), ('private', 'Private (hidden)')], default='public', max_length=50)),
                ('resume_primary_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal Profile',
                'verbose_name_plural': 'Personal Profiles',
                'db_table': 'personal_profiles',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['account_type'], name='users_account_e502f1_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_verified'], name='users_is_veri_63cd6e_idx'),
        ),
        migrations.AddIndex(
            model_name='companyprofile',
            index=models.Index(fields=['user'], name='company_pro_user_id_8e94d9_idx'),
        ),
        migrations.AddIndex(
            model_name='companyprofile',
            index=models.Index(fields=['verification_status'], name='company_pro_verific_9a7930_idx'),
        ),
        migrations.AddIndex(
            model_name='companyprofile',
            index=models.Index(fields=['company_name'], name='company_pro_company_43f4ac_idx'),
        ),
        migrations.AddIndex(
            model_name='personalprofile',
            index=models.Index(fields=['user'], name='personal_pr_user_id_5011e9_idx'),
        ),
        migrations.AddIndex(
            model_name='personalprofile',
            index=models.Index(fields=['profile_visibility'], name='personal_pr_profile_3d2b3d_idx'),
        ),
    ]
