# Generated by Django 6.0.1 on 2026-01-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_companyprofile_facebook_companyprofile_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalprofile',
            name='salary_currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD - US Dollar'), ('EUR', 'EUR - Euro'), ('GBP', 'GBP - British Pound'), ('NGN', 'NGN - Nigerian Naira'), ('CAD', 'CAD - Canadian Dollar'), ('AUD', 'AUD - Australian Dollar'), ('JPY', 'JPY - Japanese Yen'), ('CNY', 'CNY - Chinese Yuan'), ('INR', 'INR - Indian Rupee')], default='USD', max_length=10),
        ),
    ]
