# Generated by Django 6.0.1 on 2026-01-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_personalprofile_salary_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalprofile',
            name='remote_preference',
            field=models.CharField(choices=[('remote', 'Fully Remote'), ('hybrid', 'Hybrid (Remote + Office)'), ('on-site', 'On-site Only'), ('no_preference', 'No Preference')], default='no_preference', help_text='Preferred work location type', max_length=50),
        ),
    ]
