# Generated by Django 6.0.1 on 2026-01-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_remote_preference_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='locations',
            field=models.JSONField(blank=True, default=list, help_text='Array of location objects: [{"address": "123 Main St", "city": "SF", "state": "CA", "country": "USA", "is_hq": true, "lat": 37.7749, "lng": -122.4194}]'),
        ),
    ]
