# Generated by Django 6.0.1 on 2026-01-13 15:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_convert_benefits_to_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailPreferences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_frequency', models.CharField(choices=[('instant', 'Instant (real-time notifications)'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest'), ('off', 'Off (in-app only)')], default='instant', help_text='Default email notification frequency', max_length=20)),
                ('notify_new_application', models.BooleanField(default=True, help_text='New job recommendations')),
                ('notify_application_status_changed', models.BooleanField(default=True, help_text='When an application status changes')),
                ('notify_new_message', models.BooleanField(default=True, help_text='When someone sends you a message')),
                ('notify_profile_viewed', models.BooleanField(default=True, help_text='When someone views your profile')),
                ('notify_new_follower', models.BooleanField(default=True, help_text='When someone follows you')),
                ('notify_followed_company_job', models.BooleanField(default=True, help_text='New jobs from companies you follow')),
                ('notify_interview_scheduled', models.BooleanField(default=True, help_text='Interview invitations and schedule changes')),
                ('notify_job_recommendations', models.BooleanField(default=True, help_text='Weekly/daily job recommendations')),
                ('notify_new_applicant', models.BooleanField(default=True, help_text='New applications received')),
                ('notify_screening_complete', models.BooleanField(default=True, help_text='Resume screening completed')),
                ('notify_job_expiring_soon', models.BooleanField(default=True, help_text='Reminders for jobs about to expire')),
                ('notify_applicant_response', models.BooleanField(default=True, help_text='When applicants respond to messages')),
                ('notify_new_company_follower', models.BooleanField(default=True, help_text='When someone follows your company')),
                ('unsubscribe_token', models.CharField(blank=True, default=None, help_text='Token for email unsubscribe links', max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_digest_sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Preferences',
                'verbose_name_plural': 'Email Preferences',
                'db_table': 'email_preferences',
                'indexes': [models.Index(fields=['user'], name='email_prefe_user_id_d6c413_idx'), models.Index(fields=['unsubscribe_token'], name='email_prefe_unsubsc_651ba1_idx')],
            },
        ),
    ]
