# Generated by Django 6.0.1 on 2026-01-14 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_2fa_and_session_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accountdeletionlog',
            new_name='account_del_deleted_534e28_idx',
            old_name='deletion_logs_date_idx',
        ),
        migrations.RenameIndex(
            model_name='accountdeletionlog',
            new_name='account_del_account_31bff1_idx',
            old_name='deletion_logs_type_idx',
        ),
        migrations.RenameIndex(
            model_name='apikey',
            new_name='api_keys_user_id_6e7352_idx',
            old_name='api_keys_user_id_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='apikey',
            new_name='api_keys_key_291dcc_idx',
            old_name='api_keys_key_idx',
        ),
        migrations.RenameIndex(
            model_name='profileview',
            new_name='profile_vie_profile_69fac9_idx',
            old_name='profile_views_profile_user_idx',
        ),
        migrations.RenameIndex(
            model_name='profileview',
            new_name='profile_vie_viewer__cc977a_idx',
            old_name='profile_views_viewer_idx',
        ),
        migrations.RenameIndex(
            model_name='usersession',
            new_name='user_sessio_user_id_3a59ae_idx',
            old_name='user_sessions_user_activity_idx',
        ),
        migrations.RenameIndex(
            model_name='usersession',
            new_name='user_sessio_session_cc84b9_idx',
            old_name='user_sessions_key_idx',
        ),
    ]
