# Generated by Django 6.0.1 on 2026-01-17 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_deletion_logs_date_idx_account_del_deleted_534e28_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Your full name as it should appear on resumes', max_length=200)),
                ('professional_title', models.CharField(blank=True, help_text='Current or target job title (e.g., "Senior Software Engineer")', max_length=200)),
                ('phone', models.CharField(blank=True, help_text='Primary phone number', max_length=20)),
                ('location', models.CharField(blank=True, help_text='Location (city, region, or country)', max_length=200)),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('portfolio_url', models.URLField(blank=True, help_text='Portfolio or personal website')),
                ('github_url', models.URLField(blank=True, help_text='GitHub profile URL (for technical roles)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Generic profile used for resume headers and contact info', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
