# Generated by Django 6.0.1 on 2026-01-12 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_add_job_analytics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobanalytics',
            name='job',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='jobs_job_company_797da4_idx',
            old_name='jobs_job_company_status_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='jobs_job_status_a9561c_idx',
            old_name='jobs_job_status_published_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='jobs_job_locatio_da8f26_idx',
            old_name='jobs_job_location_status_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='jobs_job_employm_93b524_idx',
            old_name='jobs_job_employment_status_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='jobs_job_experie_879db8_idx',
            old_name='jobs_job_experience_status_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='jobs_job_is_feat_5919f4_idx',
            old_name='jobs_job_featured_status_idx',
        ),
        migrations.RenameIndex(
            model_name='jobview',
            new_name='jobs_jobvie_job_id_f6a7d8_idx',
            old_name='jobs_jobview_job_viewed_idx',
        ),
        migrations.RenameIndex(
            model_name='jobview',
            new_name='jobs_jobvie_user_id_1f2d90_idx',
            old_name='jobs_jobview_user_viewed_idx',
        ),
        migrations.RenameIndex(
            model_name='savedjob',
            new_name='jobs_savedj_user_id_ce1347_idx',
            old_name='jobs_savedjob_user_saved_idx',
        ),
        migrations.DeleteModel(
            name='JobAnalytics',
        ),
    ]
