# Generated by Django 6.0.1 on 2026-01-14 16:46

from django.db import migrations
from geopy.geocoders import Nominatim
from geopy.exc import GeocoderTimedOut, GeocoderUnavailable


def geocode_existing_jobs(apps, schema_editor):
    """Geocode existing jobs that don't have coordinates."""
    Job = apps.get_model('jobs', 'Job')

    geolocator = Nominatim(user_agent="hiresight-migration-geocoding")

    for job in Job.objects.filter(latitude__isnull=True, longitude__isnull=True, is_remote=False).exclude(location=''):
        try:
            location = geolocator.geocode(job.location, timeout=10)
            if location:
                job.latitude = location.latitude
                job.longitude = location.longitude
                job.save(update_fields=['latitude', 'longitude'])
        except (GeocoderTimedOut, GeocoderUnavailable):
            # Skip if geocoding service is unavailable
            continue
        except Exception:
            # Skip any other errors
            continue


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_add_location_coordinates'),
    ]

    operations = [
        migrations.RunPython(geocode_existing_jobs, migrations.RunPython.noop),
    ]
