# Generated by Django 6.0.1 on 2026-02-06 08:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='🏅', max_length=10)),
                ('type', models.CharField(choices=[('first_attempt_pass', 'First Attempt Pass'), ('perfect_score', 'Perfect Score'), ('speed_demon', 'Speed Demon'), ('consistency_king', 'Consistency King'), ('skill_master', 'Skill Master')], max_length=50)),
                ('criteria', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuestionPool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill_name', models.CharField(db_index=True, help_text='e.g., Python, React, SQL', max_length=100)),
                ('difficulty', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], max_length=20)),
                ('question_type', models.CharField(choices=[('MULTIPLE_CHOICE', 'Multiple Choice'), ('TRUE_FALSE', 'True/False'), ('CODE', 'Coding Challenge'), ('ESSAY', 'Essay/Written'), ('FILL_BLANK', 'Fill in the Blank')], default='MULTIPLE_CHOICE', max_length=20)),
                ('question', models.TextField(help_text='The question text')),
                ('options', models.JSONField(blank=True, default=list, help_text='Answer options for multiple choice')),
                ('correct_answer', models.JSONField(help_text='Correct answer(s)')),
                ('explanation', models.TextField(blank=True, help_text='Explanation of the correct answer')),
                ('points', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('estimated_time_seconds', models.PositiveIntegerField(default=60, help_text='Estimated time to answer')),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('times_correct', models.PositiveIntegerField(default=0)),
                ('average_time_taken', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Verified by admin')),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_count', models.PositiveIntegerField(default=0)),
                ('explanation_upvotes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Question Pool',
                'verbose_name_plural': 'Question Pools',
                'ordering': ['skill_name', 'difficulty'],
            },
        ),
        migrations.CreateModel(
            name='QuestionDiscussion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upvotes', models.ManyToManyField(blank=True, related_name='upvoted_discussions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='assessments.questionpool')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillAssessmentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned'), ('EXPIRED', 'Expired')], default='IN_PROGRESS', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('frozen_questions', models.JSONField(default=list, help_text='Questions generated for this attempt')),
                ('answers', models.JSONField(default=dict, help_text="User's answers keyed by question ID")),
                ('score', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('points_possible', models.PositiveIntegerField(default=0)),
                ('question_results', models.JSONField(default=dict, help_text='Per-question correctness')),
                ('time_taken_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('time_limit_exceeded', models.BooleanField(default=False)),
                ('is_practice_mode', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assessment Attempt',
                'verbose_name_plural': 'Assessment Attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BookmarkedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_questions', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='assessments.questionpool')),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookmarked_questions', to='assessments.skillassessmentattempt')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('skill_name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField()),
                ('test_type', models.CharField(choices=[('STATIC', 'Static (Fixed Questions)'), ('DYNAMIC', 'Dynamic (Random from Pool)')], default='DYNAMIC', max_length=20)),
                ('difficulty', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], default='BEGINNER', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(180)])),
                ('passing_score', models.PositiveIntegerField(default=70, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)])),
                ('questions', models.JSONField(blank=True, default=list, help_text='Static questions')),
                ('question_count', models.PositiveIntegerField(default=20, help_text='Number of questions to generate')),
                ('question_pool_filters', models.JSONField(blank=True, default=dict, help_text="Filters for question pool: {'difficulty': 'INTERMEDIATE', 'types': ['MULTIPLE_CHOICE']}")),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('required_skills', models.JSONField(default=list, help_text='Skills required to see this test')),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('total_passed', models.PositiveIntegerField(default=0)),
                ('average_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('average_completion_time', models.FloatField(default=0.0, help_text='Average time in minutes')),
                ('max_retakes_per_day', models.PositiveIntegerField(default=3, help_text='Daily retake cap per user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Skill Test',
                'verbose_name_plural': 'Skill Tests',
                'ordering': ['skill_name', 'difficulty'],
                'indexes': [models.Index(fields=['skill_name', 'difficulty', 'is_active'], name='assessments_skill_n_dde22a_idx'), models.Index(fields=['is_active', 'is_featured'], name='assessments_is_acti_c94f3f_idx'), models.Index(fields=['slug'], name='assessments_slug_3b1dde_idx')],
            },
        ),
        migrations.CreateModel(
            name='SkillBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('badge_name', models.CharField(max_length=255)),
                ('badge_level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], max_length=20)),
                ('badge_image_url', models.ImageField(blank=True, null=True, upload_to='badges/')),
                ('issued_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('verification_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('verification_url', models.URLField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='badge', to='assessments.skillassessmentattempt')),
                ('shared_with_companies', models.ManyToManyField(blank=True, related_name='viewed_badges', to='accounts.companyprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_badges', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='assessments.skilltest')),
            ],
            options={
                'verbose_name': 'Skill Badge',
                'verbose_name_plural': 'Skill Badges',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.AddField(
            model_name='skillassessmentattempt',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessments.skilltest'),
        ),
        migrations.CreateModel(
            name='AssessmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('tests', models.ManyToManyField(blank=True, related_name='categories', to='assessments.skilltest')),
            ],
            options={
                'verbose_name': 'Assessment Category',
                'verbose_name_plural': 'Assessment Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('skill_focus', models.CharField(max_length=100)),
                ('is_public', models.BooleanField(default=True)),
                ('max_members', models.PositiveIntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_study_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('prize_description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.skilltest')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='assessments.studygroup')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='StudyGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('MEMBER', 'Member')], default='MEMBER', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='assessments.studygroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
        migrations.AddField(
            model_name='studygroup',
            name='members',
            field=models.ManyToManyField(related_name='study_groups', through='assessments.StudyGroupMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by', to='assessments.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='questionpool',
            index=models.Index(fields=['skill_name', 'difficulty', 'is_active'], name='assessments_skill_n_772f19_idx'),
        ),
        migrations.AddIndex(
            model_name='questionpool',
            index=models.Index(fields=['question_type', 'is_active'], name='assessments_questio_56b051_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookmarkedquestion',
            unique_together={('user', 'question')},
        ),
        migrations.AddIndex(
            model_name='skillbadge',
            index=models.Index(fields=['user', 'is_public'], name='assessments_user_id_3cfa2c_idx'),
        ),
        migrations.AddIndex(
            model_name='skillbadge',
            index=models.Index(fields=['verification_code'], name='assessments_verific_1683ba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='skillbadge',
            unique_together={('user', 'test')},
        ),
        migrations.AddIndex(
            model_name='skillassessmentattempt',
            index=models.Index(fields=['user', 'test', 'status'], name='assessments_user_id_41654a_idx'),
        ),
        migrations.AddIndex(
            model_name='skillassessmentattempt',
            index=models.Index(fields=['status', 'completed_at'], name='assessments_status_4e245a_idx'),
        ),
        migrations.AddIndex(
            model_name='skillassessmentattempt',
            index=models.Index(fields=['user', '-started_at'], name='assessments_user_id_4644b6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studygroupmembership',
            unique_together={('user', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together={('user', 'achievement')},
        ),
    ]
