# Generated by Django 6.0.1 on 2026-01-17 15:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('skill_name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('test_type', models.CharField(choices=[('MULTIPLE_CHOICE', 'Multiple Choice'), ('CODE', 'Coding Challenge'), ('ESSAY', 'Essay/Written'), ('MIXED', 'Mixed Format')], max_length=20)),
                ('difficulty', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('passing_score', models.PositiveIntegerField(default=70)),
                ('questions', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['skill_name', 'difficulty'],
                'indexes': [models.Index(fields=['skill_name', 'difficulty'], name='assessments_skill_n_e17d7e_idx'), models.Index(fields=['is_active'], name='assessments_is_acti_b95444_idx')],
            },
        ),
        migrations.CreateModel(
            name='SkillAssessmentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], default='IN_PROGRESS', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('time_taken_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessments.skilltest')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('badge_name', models.CharField(blank=True, max_length=255)),
                ('badge_image_url', models.URLField(blank=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('verification_code', models.CharField(blank=True, max_length=50)),
                ('is_public', models.BooleanField(default=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assessments.skillassessmentattempt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_badges', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.skilltest')),
            ],
            options={
                'ordering': ['-issued_at'],
                'unique_together': {('user', 'test')},
            },
        ),
        migrations.AddIndex(
            model_name='skillassessmentattempt',
            index=models.Index(fields=['user', 'test'], name='assessments_user_id_8c4a9b_idx'),
        ),
        migrations.AddIndex(
            model_name='skillassessmentattempt',
            index=models.Index(fields=['status', 'completed_at'], name='assessments_status_4e245a_idx'),
        ),
    ]
