# Generated by Django 6.0.1 on 2026-01-17 17:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userprofile'),
        ('assessments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Assessment Category',
                'verbose_name_plural': 'Assessment Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuestionPool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill_name', models.CharField(db_index=True, help_text='e.g., Python, React, SQL', max_length=100)),
                ('difficulty', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], max_length=20)),
                ('question_type', models.CharField(choices=[('MULTIPLE_CHOICE', 'Multiple Choice'), ('TRUE_FALSE', 'True/False'), ('CODE', 'Coding Challenge'), ('ESSAY', 'Essay/Written'), ('FILL_BLANK', 'Fill in the Blank')], default='MULTIPLE_CHOICE', max_length=20)),
                ('question', models.TextField(help_text='The question text')),
                ('options', models.JSONField(blank=True, default=list, help_text='Answer options for multiple choice')),
                ('correct_answer', models.JSONField(help_text='Correct answer(s)')),
                ('explanation', models.TextField(blank=True, help_text='Explanation of the correct answer')),
                ('points', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('estimated_time_seconds', models.PositiveIntegerField(default=60, help_text='Estimated time to answer')),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('times_correct', models.PositiveIntegerField(default=0)),
                ('average_time_taken', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Verified by admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Question Pool',
                'verbose_name_plural': 'Question Pools',
                'ordering': ['skill_name', 'difficulty'],
            },
        ),
        migrations.AlterModelOptions(
            name='skillassessmentattempt',
            options={'ordering': ['-started_at'], 'verbose_name': 'Assessment Attempt', 'verbose_name_plural': 'Assessment Attempts'},
        ),
        migrations.AlterModelOptions(
            name='skillbadge',
            options={'ordering': ['-issued_at'], 'verbose_name': 'Skill Badge', 'verbose_name_plural': 'Skill Badges'},
        ),
        migrations.AlterModelOptions(
            name='skilltest',
            options={'ordering': ['skill_name', 'difficulty'], 'verbose_name': 'Skill Test', 'verbose_name_plural': 'Skill Tests'},
        ),
        migrations.RemoveIndex(
            model_name='skillassessmentattempt',
            name='assessments_user_id_8c4a9b_idx',
        ),
        migrations.RemoveIndex(
            model_name='skilltest',
            name='assessments_skill_n_e17d7e_idx',
        ),
        migrations.RemoveIndex(
            model_name='skilltest',
            name='assessments_is_acti_b95444_idx',
        ),
        migrations.AddField(
            model_name='skillassessmentattempt',
            name='frozen_questions',
            field=models.JSONField(default=list, help_text='Questions generated for this attempt'),
        ),
        migrations.AddField(
            model_name='skillassessmentattempt',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skillassessmentattempt',
            name='points_earned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skillassessmentattempt',
            name='points_possible',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skillassessmentattempt',
            name='question_results',
            field=models.JSONField(default=dict, help_text='Per-question correctness'),
        ),
        migrations.AddField(
            model_name='skillassessmentattempt',
            name='time_limit_exceeded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skillassessmentattempt',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='skillbadge',
            name='badge_level',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skillbadge',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='skillbadge',
            name='shared_with_companies',
            field=models.ManyToManyField(blank=True, related_name='viewed_badges', to='accounts.companyprofile'),
        ),
        migrations.AddField(
            model_name='skillbadge',
            name='verification_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='skillbadge',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skilltest',
            name='average_completion_time',
            field=models.FloatField(default=0.0, help_text='Average time in minutes'),
        ),
        migrations.AddField(
            model_name='skilltest',
            name='average_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='skilltest',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skilltest',
            name='question_count',
            field=models.PositiveIntegerField(default=20, help_text='Number of questions to generate'),
        ),
        migrations.AddField(
            model_name='skilltest',
            name='question_pool_filters',
            field=models.JSONField(blank=True, default=dict, help_text="Filters for question pool: {'difficulty': 'INTERMEDIATE', 'types': ['MULTIPLE_CHOICE']}"),
        ),
        migrations.AddField(
            model_name='skilltest',
            name='required_skills',
            field=models.JSONField(default=list, help_text='Skills required to see this test'),
        ),
        migrations.AddField(
            model_name='skilltest',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skilltest',
            name='total_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skilltest',
            name='total_passed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skilltest',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='skillassessmentattempt',
            name='answers',
            field=models.JSONField(default=dict, help_text="User's answers keyed by question ID"),
        ),
        migrations.AlterField(
            model_name='skillassessmentattempt',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='skillassessmentattempt',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='skillassessmentattempt',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned'), ('EXPIRED', 'Expired')], default='IN_PROGRESS', max_length=20),
        ),
        migrations.AlterField(
            model_name='skillassessmentattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='skillbadge',
            name='attempt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='badge', to='assessments.skillassessmentattempt'),
        ),
        migrations.AlterField(
            model_name='skillbadge',
            name='badge_image_url',
            field=models.ImageField(blank=True, null=True, upload_to='badges/'),
        ),
        migrations.AlterField(
            model_name='skillbadge',
            name='badge_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='skillbadge',
            name='issued_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='skillbadge',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='assessments.skilltest'),
        ),
        migrations.AlterField(
            model_name='skillbadge',
            name='verification_code',
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='skilltest',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='skilltest',
            name='difficulty',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], default='BEGINNER', max_length=20),
        ),
        migrations.AlterField(
            model_name='skilltest',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='skilltest',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='skilltest',
            name='passing_score',
            field=models.PositiveIntegerField(default=70, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='skilltest',
            name='questions',
            field=models.JSONField(blank=True, default=list, help_text='Static questions'),
        ),
        migrations.AlterField(
            model_name='skilltest',
            name='test_type',
            field=models.CharField(choices=[('STATIC', 'Static (Fixed Questions)'), ('DYNAMIC', 'Dynamic (Random from Pool)')], default='DYNAMIC', max_length=20),
        ),
        migrations.AddIndex(
            model_name='skillassessmentattempt',
            index=models.Index(fields=['user', 'test', 'status'], name='assessments_user_id_41654a_idx'),
        ),
        migrations.AddIndex(
            model_name='skillassessmentattempt',
            index=models.Index(fields=['user', '-started_at'], name='assessments_user_id_4644b6_idx'),
        ),
        migrations.AddIndex(
            model_name='skillbadge',
            index=models.Index(fields=['user', 'is_public'], name='assessments_user_id_3cfa2c_idx'),
        ),
        migrations.AddIndex(
            model_name='skillbadge',
            index=models.Index(fields=['verification_code'], name='assessments_verific_1683ba_idx'),
        ),
        migrations.AddIndex(
            model_name='skilltest',
            index=models.Index(fields=['skill_name', 'difficulty', 'is_active'], name='assessments_skill_n_dde22a_idx'),
        ),
        migrations.AddIndex(
            model_name='skilltest',
            index=models.Index(fields=['is_active', 'is_featured'], name='assessments_is_acti_c94f3f_idx'),
        ),
        migrations.AddIndex(
            model_name='skilltest',
            index=models.Index(fields=['slug'], name='assessments_slug_3b1dde_idx'),
        ),
        migrations.AddField(
            model_name='assessmentcategory',
            name='tests',
            field=models.ManyToManyField(blank=True, related_name='categories', to='assessments.skilltest'),
        ),
        migrations.AddField(
            model_name='questionpool',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='questionpool',
            index=models.Index(fields=['skill_name', 'difficulty', 'is_active'], name='assessments_skill_n_772f19_idx'),
        ),
        migrations.AddIndex(
            model_name='questionpool',
            index=models.Index(fields=['question_type', 'is_active'], name='assessments_questio_56b051_idx'),
        ),
    ]
