# Generated by Django 6.0.1 on 2026-01-21 16:46

import apps.resumes.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Unique UUID for this resume', unique=True)),
                ('title', models.CharField(help_text="Resume title (e.g., 'Software Engineer Resume')", max_length=200)),
                ('file', models.FileField(help_text='Resume file (PDF or DOCX, max 5MB)', upload_to=apps.resumes.models.resume_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'txt'])])),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('original_filename', models.CharField(help_text='Original filename before upload', max_length=255)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('parsing', 'Parsing'), ('parsed', 'Parsed'), ('failed', 'Failed')], db_index=True, default='uploaded', max_length=20)),
                ('is_primary', models.BooleanField(db_index=True, default=False, help_text='Is this the primary resume for the user?')),
                ('parsed_text', models.TextField(blank=True, help_text='Full text extracted from resume')),
                ('skills', models.JSONField(blank=True, default=list, help_text='Skills extracted from resume')),
                ('experience_years', models.FloatField(blank=True, help_text='Years of experience extracted', null=True)),
                ('education', models.JSONField(blank=True, default=list, help_text='Education details extracted')),
                ('contact_info', models.JSONField(blank=True, default=dict, help_text='Contact information extracted')),
                ('certifications', models.JSONField(blank=True, default=list, help_text='Certifications extracted from resume')),
                ('uploaded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if parsing failed')),
                ('parse_attempts', models.PositiveIntegerField(default=0, help_text='Number of parsing attempts')),
                ('last_parse_attempt', models.DateTimeField(blank=True, help_text='Last time parsing was attempted', null=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number of this resume')),
                ('version_notes', models.TextField(blank=True, help_text='Notes about what changed in this version')),
                ('is_latest_version', models.BooleanField(db_index=True, default=True, help_text='Is this the latest version in the version chain?')),
                ('parent_version', models.ForeignKey(blank=True, help_text='Parent version this was derived from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_versions', to='resumes.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeOptimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ats_score', models.FloatField(default=0)),
                ('action_verb_score', models.FloatField(default=0)),
                ('quantifiable_score', models.FloatField(default=0)),
                ('formatting_score', models.FloatField(default=0)),
                ('keyword_score', models.FloatField(default=0)),
                ('overall_score', models.FloatField(default=0)),
                ('action_verb_analysis', models.JSONField(default=dict)),
                ('quantifiable_analysis', models.JSONField(default=dict)),
                ('keyword_analysis', models.JSONField(default=dict)),
                ('formatting_issues', models.JSONField(default=list)),
                ('suggestions', models.JSONField(default=list)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='optimization', to='resumes.resume')),
            ],
            options={
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeRewriteDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rewritten_text', models.TextField()),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('highlights', models.TextField(blank=True)),
                ('metrics_focus', models.TextField(blank=True)),
                ('job_description', models.TextField(blank=True)),
                ('optimization_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('preview', 'Preview'), ('saved', 'Saved')], default='preview', max_length=10)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewrite_drafts', to='resumes.resume')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('suggestion', models.TextField()),
                ('example_before', models.TextField(blank=True)),
                ('example_after', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('optimization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_suggestions', to='resumes.resumeoptimization')),
            ],
            options={
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['user', '-uploaded_at'], name='resumes_res_user_id_582ba0_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['user', 'is_primary'], name='resumes_res_user_id_ce3f75_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['status', '-uploaded_at'], name='resumes_res_status_10b2f2_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['user', 'is_latest_version'], name='resumes_res_user_id_a9b289_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['user', 'version'], name='resumes_res_user_id_dd2e5d_idx'),
        ),
        migrations.AddConstraint(
            model_name='resume',
            constraint=models.CheckConstraint(condition=models.Q(('file_size__isnull', True), ('file_size__lte', 5242880), _connector='OR'), name='file_size_limit'),
        ),
    ]
