# Generated by Django 6.0.1 on 2026-01-10 14:21

import apps.resumes.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Resume title (e.g., 'Software Engineer Resume')", max_length=200)),
                ('file', models.FileField(help_text='Resume file (PDF or DOCX, max 5MB)', upload_to=apps.resumes.models.resume_upload_path)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('original_filename', models.CharField(help_text='Original filename before upload', max_length=255)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('parsing', 'Parsing'), ('parsed', 'Parsed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text='Is this the primary resume for the user?')),
                ('parsed_text', models.TextField(blank=True, help_text='Full text extracted from resume')),
                ('skills', models.JSONField(default=list, help_text='Skills extracted from resume')),
                ('experience_years', models.FloatField(blank=True, help_text='Years of experience extracted', null=True)),
                ('education', models.JSONField(default=list, help_text='Education details extracted')),
                ('contact_info', models.JSONField(default=dict, help_text='Contact information extracted')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if parsing failed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'unique_together': {('user', 'is_primary')},
            },
        ),
    ]
