# Generated by Django 6.0.1 on 2026-01-11 23:26

import apps.resumes.models
import django.core.validators
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_improve_resume_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='resume',
            name='file_size_limit',
        ),
        migrations.RemoveIndex(
            model_name='resume',
            name='resumes_res_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='resume',
            name='resumes_res_primary_idx',
        ),
        migrations.RemoveIndex(
            model_name='resume',
            name='resumes_res_upload_idx',
        ),
        migrations.RenameIndex(
            model_name='resume',
            new_name='resumes_res_user_id_582ba0_idx',
            old_name='resumes_res_user_id_upload_idx',
        ),
        migrations.RenameIndex(
            model_name='resume',
            new_name='resumes_res_user_id_ce3f75_idx',
            old_name='resumes_res_user_id_primar_idx',
        ),
        migrations.RenameIndex(
            model_name='resume',
            new_name='resumes_res_status_10b2f2_idx',
            old_name='resumes_res_status_upload_idx',
        ),
        migrations.AlterField(
            model_name='resume',
            name='contact_info',
            field=models.JSONField(blank=True, default=dict, help_text='Contact information extracted'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.JSONField(blank=True, default=list, help_text='Education details extracted'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(help_text='Resume file (PDF or DOCX, max 5MB)', upload_to=apps.resumes.models.resume_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='resume',
            name='is_primary',
            field=models.BooleanField(db_index=True, default=False, help_text='Is this the primary resume for the user?'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.JSONField(blank=True, default=list, help_text='Skills extracted from resume'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('parsing', 'Parsing'), ('parsed', 'Parsed'), ('failed', 'Failed')], db_index=True, default='uploaded', max_length=20),
        ),
        migrations.AlterField(
            model_name='resume',
            name='uploaded_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='resume',
            constraint=models.CheckConstraint(condition=models.Q(('file_size__isnull', True), ('file_size__lte', 5242880), _connector='OR'), name='file_size_limit'),
        ),
    ]
