# Generated by Django 6.0.1 on 2026-01-14 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_remove_resume_file_size_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='is_latest_version',
            field=models.BooleanField(db_index=True, default=True, help_text='Is this the latest version in the version chain?'),
        ),
        migrations.AddField(
            model_name='resume',
            name='parent_version',
            field=models.ForeignKey(blank=True, help_text='Parent version this was derived from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_versions', to='resumes.resume'),
        ),
        migrations.AddField(
            model_name='resume',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Version number of this resume'),
        ),
        migrations.AddField(
            model_name='resume',
            name='version_notes',
            field=models.TextField(blank=True, help_text='Notes about what changed in this version'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['user', 'is_latest_version'], name='resumes_res_user_id_a9b289_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['user', 'version'], name='resumes_res_user_id_dd2e5d_idx'),
        ),
    ]
