# Generated by Django 6.0.1 on 2026-01-14 12:37

import apps.resumes.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_resume_is_latest_version_resume_parent_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='certifications',
            field=models.JSONField(blank=True, default=list, help_text='Certifications extracted from resume'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(help_text='Resume file (PDF or DOCX, max 5MB)', upload_to=apps.resumes.models.resume_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'txt'])]),
        ),
        migrations.CreateModel(
            name='ResumeOptimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ats_score', models.FloatField(default=0)),
                ('action_verb_score', models.FloatField(default=0)),
                ('quantifiable_score', models.FloatField(default=0)),
                ('formatting_score', models.FloatField(default=0)),
                ('keyword_score', models.FloatField(default=0)),
                ('overall_score', models.FloatField(default=0)),
                ('action_verb_analysis', models.JSONField(default=dict)),
                ('quantifiable_analysis', models.JSONField(default=dict)),
                ('keyword_analysis', models.JSONField(default=dict)),
                ('formatting_issues', models.JSONField(default=list)),
                ('suggestions', models.JSONField(default=list)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='optimization', to='resumes.resume')),
            ],
            options={
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('suggestion', models.TextField()),
                ('example_before', models.TextField(blank=True)),
                ('example_after', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('optimization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_suggestions', to='resumes.resumeoptimization')),
            ],
            options={
                'ordering': ['priority', 'created_at'],
            },
        ),
    ]
