# Generated by Django 6.0.1 on 2026-01-14 19:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_resume_certifications_alter_resume_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Unique UUID for this resume', unique=True),
        ),
    ]
