# Generated by Django 6.0.1 on 2026-01-16 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0006_resume_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeRewriteDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rewritten_text', models.TextField()),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('highlights', models.TextField(blank=True)),
                ('metrics_focus', models.TextField(blank=True)),
                ('optimization_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('preview', 'Preview'), ('saved', 'Saved')], default='preview', max_length=10)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewrite_drafts', to='resumes.resume')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
