# Generated by Django 6.0.1 on 2026-01-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0007_resumerewritedraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumerewritedraft',
            name='job_description',
            field=models.TextField(blank=True),
        ),
    ]
