# Generated by Django 6.0.1 on 2026-01-12 11:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_convert_benefits_to_json'),
        ('jobs', '0004_remove_jobanalytics_job_and_more'),
        ('resumes', '0003_remove_resume_file_size_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Session name/description', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Current screening status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When screening session was created')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When screening session was completed', null=True)),
                ('total_resumes', models.PositiveIntegerField(default=0, help_text='Total number of resumes in session')),
                ('processed_resumes', models.PositiveIntegerField(default=0, help_text='Number of resumes processed successfully')),
                ('failed_resumes', models.PositiveIntegerField(default=0, help_text='Number of resumes that failed processing')),
                ('average_match_score', models.FloatField(blank=True, help_text='Average match score across all resumes', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Screening parameters and settings')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_sessions', to='accounts.companyprofile')),
                ('created_by', models.ForeignKey(help_text='Who initiated the screening session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_screening_sessions', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, help_text='Specific job being screened for (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screening_sessions', to='jobs.job')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_score', models.IntegerField(help_text='AI-generated match score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('match_details', models.JSONField(blank=True, default=dict, help_text='Detailed match analysis')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Processing status', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When screening was completed', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('is_shortlisted', models.BooleanField(db_index=True, default=False, help_text='Has this candidate been shortlisted?')),
                ('notes', models.TextField(blank=True, help_text='Recruiter notes about this screening result')),
                ('rating', models.IntegerField(blank=True, help_text='Manual rating (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('job', models.ForeignKey(blank=True, help_text='Job being matched against (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screening_results', to='jobs.job')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_results', to='resumes.resume')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='screening.screeningsession')),
            ],
            options={
                'ordering': ['-match_score', '-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningCriteria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('required_skills', models.JSONField(blank=True, default=list, help_text='List of required skills')),
                ('nice_to_have_skills', models.JSONField(blank=True, default=list, help_text='List of nice-to-have skills')),
                ('min_experience_years', models.FloatField(default=0, help_text='Minimum years of experience required', validators=[django.core.validators.MinValueValidator(0)])),
                ('max_experience_years', models.FloatField(blank=True, help_text='Maximum years of experience (optional)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('required_education', models.JSONField(blank=True, default=list, help_text='Required education levels')),
                ('location_preference', models.CharField(blank=True, help_text='Preferred location (optional)', max_length=200)),
                ('custom_keywords', models.JSONField(blank=True, default=list, help_text='Custom keywords to match')),
                ('weight_skills', models.FloatField(default=0.4, help_text='Weight for skills in scoring (0-1)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('weight_experience', models.FloatField(default=0.3, help_text='Weight for experience in scoring (0-1)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('weight_education', models.FloatField(default=0.2, help_text='Weight for education in scoring (0-1)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('weight_keywords', models.FloatField(default=0.1, help_text='Weight for keywords in scoring (0-1)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='screening.screeningsession')),
            ],
            options={
                'verbose_name_plural': 'Screening Criteria',
            },
        ),
        migrations.AddIndex(
            model_name='screeningsession',
            index=models.Index(fields=['company', '-created_at'], name='screening_s_company_72f680_idx'),
        ),
        migrations.AddIndex(
            model_name='screeningsession',
            index=models.Index(fields=['status', '-created_at'], name='screening_s_status_b34500_idx'),
        ),
        migrations.AddIndex(
            model_name='screeningsession',
            index=models.Index(fields=['job', '-created_at'], name='screening_s_job_id_7adce3_idx'),
        ),
        migrations.AddIndex(
            model_name='screeningresult',
            index=models.Index(fields=['session', '-match_score'], name='screening_s_session_06dd48_idx'),
        ),
        migrations.AddIndex(
            model_name='screeningresult',
            index=models.Index(fields=['resume', '-match_score'], name='screening_s_resume__6f06e4_idx'),
        ),
        migrations.AddIndex(
            model_name='screeningresult',
            index=models.Index(fields=['status', '-processed_at'], name='screening_s_status_df6485_idx'),
        ),
        migrations.AddIndex(
            model_name='screeningresult',
            index=models.Index(fields=['is_shortlisted', '-match_score'], name='screening_s_is_shor_e3286d_idx'),
        ),
        migrations.AddConstraint(
            model_name='screeningresult',
            constraint=models.CheckConstraint(condition=models.Q(('match_score__gte', 0), ('match_score__lte', 100)), name='screening_match_score_range'),
        ),
        migrations.AddConstraint(
            model_name='screeningresult',
            constraint=models.CheckConstraint(condition=models.Q(('rating__isnull', True), models.Q(('rating__gte', 1), ('rating__lte', 5)), _connector='OR'), name='screening_rating_range'),
        ),
    ]
