# Generated by Django 6.0.1 on 2026-01-21 16:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('applications', '0001_initial'),
        ('jobs', '0001_initial'),
        ('resumes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_score', models.IntegerField(default=0, help_text='AI-generated match score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('match_details', models.JSONField(blank=True, default=dict, help_text='Detailed match analysis')),
                ('screening_answers', models.JSONField(blank=True, default=dict, help_text="Candidate's answers to job screening questions")),
                ('assessment_data', models.JSONField(blank=True, default=dict, help_text='Skill assessment results and scores')),
                ('file_path', models.CharField(blank=True, help_text='Path to uploaded resume file', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Processing status', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When screening was completed', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('is_shortlisted', models.BooleanField(db_index=True, default=False, help_text='Has this candidate been shortlisted?')),
                ('notes', models.TextField(blank=True, help_text='Recruiter notes about this screening result')),
                ('rating', models.IntegerField(blank=True, help_text='Manual rating (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('application', models.ForeignKey(blank=True, help_text='Application being screened', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='screening_results', to='applications.application')),
                ('job', models.ForeignKey(blank=True, help_text='Job being matched against (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screening_results', to='jobs.job')),
                ('resume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='screening_results', to='resumes.resume')),
            ],
            options={
                'ordering': ['-match_score', '-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insight_type', models.CharField(choices=[('interview_questions', 'Interview Questions'), ('ai_notes', 'AI Notes'), ('rejection_reasons', 'Rejection Reasons'), ('resume_parsing', 'Resume Parsing')], help_text='Type of AI insight', max_length=50)),
                ('title', models.CharField(help_text='Title of the insight', max_length=255)),
                ('content', models.JSONField(default=dict, help_text='Structured insight content (varies by type)')),
                ('summary', models.TextField(blank=True, default='', help_text='Plain text summary of the insight')),
                ('model_used', models.CharField(default='mistral-7b', help_text='Mistral model version used', max_length=50)),
                ('tokens_used', models.IntegerField(default=0, help_text='Number of tokens used for generation')),
                ('generation_time', models.FloatField(default=0.0, help_text='Time in seconds to generate insight')),
                ('confidence_score', models.FloatField(default=0.0, help_text='Confidence score (0-1) of the AI insight', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_approved', models.BooleanField(default=False, help_text='Whether recruiter has approved this insight')),
                ('is_used', models.BooleanField(default=False, help_text='Whether this insight was actually used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result', models.ForeignKey(help_text='The screening result this insight is for', on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='screening.screeningresult')),
            ],
            options={
                'verbose_name': 'AI Insight',
                'verbose_name_plural': 'AI Insights',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Session name/description', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Current screening status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When screening session was created')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When screening session was completed', null=True)),
                ('total_resumes', models.PositiveIntegerField(default=0, help_text='Total number of resumes in session')),
                ('processed_resumes', models.PositiveIntegerField(default=0, help_text='Number of resumes processed successfully')),
                ('failed_resumes', models.PositiveIntegerField(default=0, help_text='Number of resumes that failed processing')),
                ('average_match_score', models.FloatField(blank=True, help_text='Average match score across all resumes', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Screening parameters and settings')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_sessions', to='accounts.companyprofile')),
                ('created_by', models.ForeignKey(help_text='Who initiated the screening session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_screening_sessions', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, help_text='Specific job being screened for (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screening_sessions', to='jobs.job')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='screeningresult',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='screening.screeningsession'),
        ),
        migrations.CreateModel(
            name='ScreeningCriteria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('required_skills', models.JSONField(blank=True, default=list, help_text='List of required skills')),
                ('nice_to_have_skills', models.JSONField(blank=True, default=list, help_text='List of nice-to-have skills')),
                ('min_experience_years', models.FloatField(default=0, help_text='Minimum years of experience required', validators=[django.core.validators.MinValueValidator(0)])),
                ('max_experience_years', models.FloatField(blank=True, help_text='Maximum years of experience (optional)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('required_education', models.JSONField(blank=True, default=list, help_text='Required education levels')),
                ('location_preference', models.CharField(blank=True, help_text='Preferred location (optional)', max_length=200)),
                ('custom_keywords', models.JSONField(blank=True, default=list, help_text='Custom keywords to match')),
                ('weight_skills', models.FloatField(default=0.3, help_text='Weight for skills in scoring (0-1)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('weight_experience', models.FloatField(default=0.2, help_text='Weight for experience in scoring (0-1)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('weight_education', models.FloatField(default=0.2, help_text='Weight for education in scoring (0-1)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('weight_keywords', models.FloatField(default=0.1, help_text='Weight for keywords in scoring (0-1)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('weight_screening_questions', models.FloatField(default=0.1, help_text='Weight for screening question answers in scoring (0-1)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('weight_assessments', models.FloatField(default=0.1, help_text='Weight for skill assessments in scoring (0-1)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('screening_questions_config', models.JSONField(blank=True, default=dict, help_text='Configuration for how to score screening questions')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='screening.screeningsession')),
            ],
            options={
                'verbose_name_plural': 'Screening Criteria',
            },
        ),
        migrations.CreateModel(
            name='ProgressUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('update_type', models.CharField(choices=[('upload_started', 'Upload Started'), ('upload_progress', 'Upload Progress'), ('upload_completed', 'Upload Completed'), ('screening_started', 'Screening Started'), ('screening_progress', 'Screening Progress'), ('screening_completed', 'Screening Completed'), ('result_analyzed', 'Result Analyzed'), ('pipeline_pushed', 'Pushed to Pipeline'), ('status_changed', 'Status Changed'), ('error_occurred', 'Error Occurred')], db_index=True, help_text='Type of progress update', max_length=50)),
                ('title', models.CharField(help_text='Human-readable update title', max_length=200)),
                ('message', models.TextField(blank=True, help_text='Detailed message about progress')),
                ('progress_percent', models.IntegerField(default=0, help_text='Progress percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('current_item', models.PositiveIntegerField(blank=True, help_text='Current item being processed', null=True)),
                ('total_items', models.PositiveIntegerField(blank=True, help_text='Total items to process', null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('paused', 'Paused')], db_index=True, default='running', help_text='Update status', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if applicable')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata as JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When update was created')),
                ('result', models.ForeignKey(blank=True, help_text='Specific result (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='screening.screeningresult')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='screening.screeningsession')),
            ],
            options={
                'verbose_name_plural': 'Progress Updates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsightFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.CharField(choices=[('helpful', 'Helpful'), ('partially_helpful', 'Partially Helpful'), ('not_helpful', 'Not Helpful'), ('incorrect', 'Incorrect')], help_text='Rating of the insight', max_length=20)),
                ('comment', models.TextField(blank=True, default='', help_text='Optional detailed feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('insight', models.ForeignKey(help_text='The insight this feedback is for', on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='screening.aiinsight')),
                ('user', models.ForeignKey(help_text='User who provided feedback', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_insight_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Insight Feedback',
                'verbose_name_plural': 'Insight Feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['insight', '-created_at'], name='insight_feedback_idx'), models.Index(fields=['rating', '-created_at'], name='insight_rating_idx')],
            },
        ),
        migrations.CreateModel(
            name='PipelineIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('pushed', 'Pushed to Pipeline'), ('rejected', 'Rejected from Pipeline'), ('hired', 'Hired'), ('withdrawn', 'Withdrawn')], db_index=True, default='pending', help_text='Current pipeline status', max_length=20)),
                ('pushed_at', models.DateTimeField(auto_now_add=True, help_text='When candidate was pushed to pipeline')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('pipeline_id', models.CharField(blank=True, help_text='External pipeline system ID (if applicable)', max_length=100)),
                ('pipeline_url', models.URLField(blank=True, help_text='Link to candidate in pipeline system')),
                ('pipeline_stage', models.CharField(blank=True, help_text='Current stage in hiring pipeline', max_length=100)),
                ('stage_updated_at', models.DateTimeField(blank=True, help_text='When stage was last updated', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about pipeline integration')),
                ('last_synced', models.DateTimeField(blank=True, help_text='Last time data was synced with pipeline', null=True)),
                ('sync_failed', models.BooleanField(default=False, help_text='Has sync with pipeline failed?')),
                ('sync_error', models.TextField(blank=True, help_text='Sync error details if failed')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_integrations', to='accounts.companyprofile')),
                ('job', models.ForeignKey(help_text='Job being applied for', null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.job')),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_integration', to='screening.screeningresult')),
            ],
            options={
                'verbose_name_plural': 'Pipeline Integrations',
                'ordering': ['-pushed_at'],
                'indexes': [models.Index(fields=['job', 'status'], name='screening_p_job_id_85d548_idx'), models.Index(fields=['company', '-pushed_at'], name='screening_p_company_50a939_idx'), models.Index(fields=['status', '-pushed_at'], name='screening_p_status_e3fea6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='aiinsight',
            index=models.Index(fields=['result', 'insight_type'], name='ai_insight_result_type_idx'),
        ),
        migrations.AddIndex(
            model_name='aiinsight',
            index=models.Index(fields=['insight_type', '-created_at'], name='ai_insight_type_date_idx'),
        ),
        migrations.AddIndex(
            model_name='aiinsight',
            index=models.Index(fields=['is_approved', '-created_at'], name='ai_insight_approved_idx'),
        ),
        migrations.AddIndex(
            model_name='screeningsession',
            index=models.Index(fields=['company', '-created_at'], name='screening_s_company_72f680_idx'),
        ),
        migrations.AddIndex(
            model_name='screeningsession',
            index=models.Index(fields=['status', '-created_at'], name='screening_s_status_b34500_idx'),
        ),
        migrations.AddIndex(
            model_name='screeningsession',
            index=models.Index(fields=['job', '-created_at'], name='screening_s_job_id_7adce3_idx'),
        ),
        migrations.AddIndex(
            model_name='screeningresult',
            index=models.Index(fields=['session', '-match_score'], name='screening_s_session_06dd48_idx'),
        ),
        migrations.AddIndex(
            model_name='screeningresult',
            index=models.Index(fields=['resume', '-match_score'], name='screening_s_resume__6f06e4_idx'),
        ),
        migrations.AddIndex(
            model_name='screeningresult',
            index=models.Index(fields=['status', '-processed_at'], name='screening_s_status_df6485_idx'),
        ),
        migrations.AddIndex(
            model_name='screeningresult',
            index=models.Index(fields=['is_shortlisted', '-match_score'], name='screening_s_is_shor_e3286d_idx'),
        ),
        migrations.AddConstraint(
            model_name='screeningresult',
            constraint=models.CheckConstraint(condition=models.Q(('match_score__gte', 0), ('match_score__lte', 100)), name='screening_match_score_range'),
        ),
        migrations.AddConstraint(
            model_name='screeningresult',
            constraint=models.CheckConstraint(condition=models.Q(('rating__isnull', True), models.Q(('rating__gte', 1), ('rating__lte', 5)), _connector='OR'), name='screening_rating_range'),
        ),
        migrations.AddIndex(
            model_name='progressupdate',
            index=models.Index(fields=['session', '-created_at'], name='screening_p_session_762ab5_idx'),
        ),
        migrations.AddIndex(
            model_name='progressupdate',
            index=models.Index(fields=['update_type', '-created_at'], name='screening_p_update__8802e3_idx'),
        ),
        migrations.AddIndex(
            model_name='progressupdate',
            index=models.Index(fields=['status', '-created_at'], name='screening_p_status_165f15_idx'),
        ),
    ]
