# Generated by Django 6.0.1 on 2026-01-12 15:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_remove_resume_file_size_limit_and_more'),
        ('screening', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screeningresult',
            name='match_score',
            field=models.IntegerField(default=0, help_text='AI-generated match score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='screeningresult',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='screening_results', to='resumes.resume'),
        ),
    ]
