# Generated by Django 6.0.1 on 2026-01-14 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0002_alter_screeningresult_match_score_and_more'),
        ('screening', '0005_pipelineintegration'),
    ]

    operations = [
    ]
