# Generated by Django 6.0.1 on 2026-01-20 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0010_add_screeningresult_application_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningcriteria',
            name='screening_questions_config',
            field=models.JSONField(blank=True, default=dict, help_text='Configuration for how to score screening questions'),
        ),
        migrations.AddField(
            model_name='screeningcriteria',
            name='weight_assessments',
            field=models.FloatField(default=0.1, help_text='Weight for skill assessments in scoring (0-1)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='screeningcriteria',
            name='weight_screening_questions',
            field=models.FloatField(default=0.1, help_text='Weight for screening question answers in scoring (0-1)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
