# Generated by Django 6.0.1 on 2026-01-20 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0011_screeningcriteria_screening_questions_config_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screeningcriteria',
            name='weight_experience',
            field=models.FloatField(default=0.2, help_text='Weight for experience in scoring (0-1)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='screeningcriteria',
            name='weight_skills',
            field=models.FloatField(default=0.3, help_text='Weight for skills in scoring (0-1)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
