# Generated by Django 6.0.1 on 2026-01-21 16:46

import apps.following.managers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('job_posted', 'Job Posted'), ('profile_updated', 'Profile Updated'), ('skill_added', 'Skill Added'), ('followed_user', 'Followed User'), ('unfollowed_user', 'Unfollowed User'), ('bulk_operation', 'Bulk Follow Operation')], max_length=32)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='following_a_user_id_67a388_idx'), models.Index(fields=['activity_type', 'created_at'], name='following_a_activit_080822_idx')],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('followed', models.ForeignKey(help_text='User being followed', on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(help_text='User who is following', on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['follower', 'created_at'], name='following_f_followe_f3349a_idx'), models.Index(fields=['followed', 'created_at'], name='following_f_followe_9e8e7d_idx')],
                'unique_together': {('follower', 'followed')},
            },
            managers=[
                ('objects', apps.following.managers.FollowManager()),
            ],
        ),
    ]
