# Generated by Django 6.0.1 on 2026-01-16 17:26

import apps.following.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('following', '0003_activity'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='follow',
            managers=[
                ('objects', apps.following.managers.FollowManager()),
            ],
        ),
    ]
