# Generated by Django 6.0.1 on 2026-01-21 16:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('resumes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cover_letter', models.TextField(blank=True, help_text='Optional cover letter')),
                ('portfolio_url', models.URLField(blank=True, help_text='Optional portfolio URL')),
                ('source', models.CharField(choices=[('organic', 'Organic Search'), ('referral', 'Referral'), ('social', 'Social Media'), ('direct', 'Direct Link'), ('email', 'Email Campaign'), ('partner', 'Partner/ATS'), ('other', 'Other')], db_index=True, default='organic', help_text='How the applicant discovered this job', max_length=30)),
                ('cost_to_company', models.DecimalField(blank=True, decimal_places=2, help_text='Cost allocated for this hire (ads, referral bonuses, etc.)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('screening_answers', models.JSONField(blank=True, default=dict, help_text='Answers to screening questions')),
                ('additional_notes', models.TextField(blank=True, help_text="Applicant's additional notes")),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('screening', 'Under Screening'), ('interview', 'Interview Scheduled'), ('offer', 'Offer Extended'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='pending', help_text='Current application status', max_length=20)),
                ('status_changed_at', models.DateTimeField(auto_now_add=True, help_text='When status was last changed')),
                ('match_score', models.IntegerField(blank=True, help_text='AI-generated match score (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('match_details', models.JSONField(blank=True, default=dict, help_text='Detailed match analysis from AI')),
                ('screening_notes', models.TextField(blank=True, help_text='AI-generated screening notes')),
                ('recruiter_notes', models.TextField(blank=True, help_text='Private company notes about applicant')),
                ('rating', models.IntegerField(blank=True, help_text='Recruiter rating (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_shortlisted', models.BooleanField(db_index=True, default=False, help_text='Is this applicant shortlisted?')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Custom tags for organization')),
                ('rejection_feedback', models.JSONField(blank=True, help_text='Feedback provided when rejecting the application', null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When application was submitted')),
                ('viewed_at', models.DateTimeField(blank=True, help_text='When recruiter first viewed application', null=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True, help_text='Last status change or note update')),
                ('withdrawn_at', models.DateTimeField(blank=True, help_text='When application was withdrawn', null=True)),
                ('hired_at', models.DateTimeField(blank=True, help_text='When applicant was hired', null=True)),
                ('rejected_at', models.DateTimeField(blank=True, help_text='When application was rejected', null=True)),
                ('applicant', models.ForeignKey(limit_choices_to={'account_type': 'personal'}, on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
                ('resume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='resumes.resume')),
                ('status_changed_by', models.ForeignKey(blank=True, help_text='Who changed the status', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(help_text='Note content')),
                ('is_important', models.BooleanField(db_index=True, default=False, help_text='Mark as important')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='applications.application')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('pending', 'Pending Review'), ('screening', 'Under Screening'), ('interview', 'Interview Scheduled'), ('offer', 'Offer Extended'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], help_text='Previous status (NULL for initial status)', max_length=20, null=True)),
                ('new_status', models.CharField(choices=[('pending', 'Pending Review'), ('screening', 'Under Screening'), ('interview', 'Interview Scheduled'), ('offer', 'Offer Extended'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], help_text='New status', max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for status change')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='applications.application')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_status_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job', '-applied_at'], name='application_job_id_9ac15a_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applicant', '-applied_at'], name='application_applica_4af993_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status', '-applied_at'], name='application_status_4e5767_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['match_score', '-applied_at'], name='application_match_s_ab6167_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['is_shortlisted', '-applied_at'], name='application_is_shor_49e450_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(('match_score__isnull', True), models.Q(('match_score__gte', 0), ('match_score__lte', 100)), _connector='OR'), name='match_score_range'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(('rating__isnull', True), models.Q(('rating__gte', 1), ('rating__lte', 5)), _connector='OR'), name='rating_range'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('job', 'applicant'), name='unique_application_per_job'),
        ),
        migrations.AddIndex(
            model_name='applicationnote',
            index=models.Index(fields=['application', '-created_at'], name='application_applica_2ded59_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationnote',
            index=models.Index(fields=['author', '-created_at'], name='application_author__e788b2_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationnote',
            index=models.Index(fields=['is_important', '-created_at'], name='application_is_impo_6c4b72_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationstatushistory',
            index=models.Index(fields=['application', '-changed_at'], name='application_applica_64175c_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationstatushistory',
            index=models.Index(fields=['changed_by', '-changed_at'], name='application_changed_6cf671_idx'),
        ),
    ]
