# Generated by Django 6.0.1 on 2026-01-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationstatushistory',
            name='old_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending Review'), ('screening', 'Under Screening'), ('interview', 'Interview Scheduled'), ('offer', 'Offer Extended'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], help_text='Previous status (NULL for initial status)', max_length=20, null=True),
        ),
    ]
