# Generated by Django 6.0.1 on 2026-01-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_applicationstatushistory_old_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='rejection_feedback',
            field=models.JSONField(blank=True, help_text='Feedback provided when rejecting the application', null=True),
        ),
    ]
