# Generated by Django 6.0.1 on 2026-01-14 18:36

from django.db import migrations, models
from django.core.validators import MinValueValidator


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_rejection_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cost_to_company',
            field=models.DecimalField(blank=True, help_text='Cost allocated for this hire (ads, referral bonuses, etc.)', max_digits=10, decimal_places=2, null=True, validators=[MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='application',
            name='source',
            field=models.CharField(choices=[
                ('organic', 'Organic Search'),
                ('referral', 'Referral'),
                ('social', 'Social Media'),
                ('direct', 'Direct Link'),
                ('email', 'Email Campaign'),
                ('partner', 'Partner/ATS'),
                ('other', 'Other')
            ], db_index=True, default='organic', help_text='How the applicant discovered this job', max_length=30),
        ),
    ]
