# Generated by Django 6.0.1 on 2026-01-16 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0006_geocode_existing_jobs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_applications', models.IntegerField(default=0)),
                ('applications_pending', models.IntegerField(default=0)),
                ('applications_screening', models.IntegerField(default=0)),
                ('applications_interview', models.IntegerField(default=0)),
                ('applications_offer', models.IntegerField(default=0)),
                ('applications_hired', models.IntegerField(default=0)),
                ('applications_rejected', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Application metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.CharField(max_length=500)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('results_count', models.IntegerField(default=0)),
                ('searched_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Search queries',
                'ordering': ['-searched_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyAnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_jobs', models.IntegerField(default=0)),
                ('active_jobs', models.IntegerField(default=0)),
                ('closed_jobs', models.IntegerField(default=0)),
                ('total_applications', models.IntegerField(default=0)),
                ('new_applications_today', models.IntegerField(default=0)),
                ('pending_review', models.IntegerField(default=0)),
                ('total_hires', models.IntegerField(default=0)),
                ('avg_time_to_hire', models.FloatField(blank=True, null=True)),
                ('total_job_views', models.IntegerField(default=0)),
                ('followers_count', models.IntegerField(default=0)),
                ('cost_per_hire', models.FloatField(blank=True, null=True)),
                ('applications_by_source', models.JSONField(blank=True, default=dict)),
                ('resumes_screened', models.IntegerField(default=0)),
                ('top_skills', models.JSONField(blank=True, default=list)),
                ('skill_gaps', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(limit_choices_to={'account_type': 'company'}, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['company', '-date'], name='analytics_c_company_7f27b2_idx')],
                'unique_together': {('company', 'date')},
            },
        ),
        migrations.CreateModel(
            name='JobView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('referrer', models.URLField(blank=True, max_length=500, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_views', to='jobs.job')),
                ('viewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_viewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['job', '-viewed_at'], name='analytics_j_job_id_46ea39_idx')],
            },
        ),
        migrations.CreateModel(
            name='PersonalAnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_applications', models.IntegerField(default=0)),
                ('applications_pending', models.IntegerField(default=0)),
                ('applications_screening', models.IntegerField(default=0)),
                ('applications_interview', models.IntegerField(default=0)),
                ('applications_offer', models.IntegerField(default=0)),
                ('applications_hired', models.IntegerField(default=0)),
                ('applications_rejected', models.IntegerField(default=0)),
                ('profile_views_count', models.IntegerField(default=0)),
                ('jobs_viewed_count', models.IntegerField(default=0)),
                ('jobs_saved_count', models.IntegerField(default=0)),
                ('searches_performed', models.IntegerField(default=0)),
                ('avg_match_score', models.FloatField(blank=True, null=True)),
                ('response_rate', models.FloatField(blank=True, null=True)),
                ('skill_assessments_taken', models.IntegerField(default=0)),
                ('avg_skill_assessment_score', models.FloatField(blank=True, null=True)),
                ('badges_earned', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(limit_choices_to={'account_type': 'personal'}, on_delete=django.db.models.deletion.CASCADE, related_name='personal_analytics_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', '-date'], name='analytics_p_user_id_f459a8_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ProfileView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('profile_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_profile_views_received', to=settings.AUTH_USER_MODEL)),
                ('viewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_profile_views_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['profile_owner', '-viewed_at'], name='analytics_p_profile_b0d53d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SkillAssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('score', models.FloatField()),
                ('max_score', models.FloatField(default=100.0)),
                ('passed', models.BooleanField(default=False)),
                ('badge_awarded', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(limit_choices_to={'account_type': 'personal'}, on_delete=django.db.models.deletion.CASCADE, related_name='skill_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-taken_at'],
                'indexes': [models.Index(fields=['user', '-taken_at'], name='analytics_s_user_id_80a3d3_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('profile_update', 'Profile Update'), ('resume_upload', 'Resume Upload'), ('job_post', 'Job Post'), ('job_apply', 'Job Apply'), ('message_sent', 'Message Sent'), ('follow', 'Follow'), ('unfollow', 'Unfollow')], max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='analytics_u_user_id_428695_idx'), models.Index(fields=['action_type', '-timestamp'], name='analytics_u_action__0eb0fa_idx')],
            },
        ),
    ]
