# Generated by Django 6.0.1 on 2026-01-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_culturefitassessment_diversityanalyticssnapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_applications', models.IntegerField(default=0)),
                ('applications_pending', models.IntegerField(default=0)),
                ('applications_screening', models.IntegerField(default=0)),
                ('applications_interview', models.IntegerField(default=0)),
                ('applications_offer', models.IntegerField(default=0)),
                ('applications_hired', models.IntegerField(default=0)),
                ('applications_rejected', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Application analytics',
                'ordering': ['-date'],
            },
        ),
    ]
