# Generated by Django 6.0.1 on 2026-01-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_applicationanalytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalanalyticssnapshot',
            name='assessment_trends',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='personalanalyticssnapshot',
            name='skill_summary',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='personalanalyticssnapshot',
            name='time_of_day_performance',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='personalanalyticssnapshot',
            name='weak_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='skillassessmentresult',
            name='attempt_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
