# Generated by Django 6.0.1 on 2026-01-21 16:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewFeedbackTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('interview_type', models.CharField(choices=[('PHONE', 'Phone Screen'), ('VIDEO', 'Video Call'), ('ONSITE', 'On-site'), ('TECHNICAL', 'Technical Assessment'), ('BEHAVIORAL', 'Behavioral Interview'), ('PANEL', 'Panel Interview'), ('CULTURE_FIT', 'Culture Fit Interview'), ('FINAL', 'Final Interview')], max_length=20)),
                ('questions', models.JSONField(help_text='List of questions: [{"question": "...", "type": "text|rating|boolean"}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_feedback_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interview_type', models.CharField(choices=[('PHONE', 'Phone Screen'), ('VIDEO', 'Video Call'), ('ONSITE', 'On-site'), ('TECHNICAL', 'Technical Assessment'), ('BEHAVIORAL', 'Behavioral Interview'), ('PANEL', 'Panel Interview'), ('CULTURE_FIT', 'Culture Fit Interview'), ('FINAL', 'Final Interview')], help_text='Type of interview being conducted', max_length=20)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('RESCHEDULED', 'Rescheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='SCHEDULED', max_length=20)),
                ('scheduled_date', models.DateTimeField(help_text='Date and time of the interview')),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Interview duration in minutes (15-480)', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(480)])),
                ('timezone_name', models.CharField(db_column='timezone', default='UTC', help_text='Timezone for the scheduled date (e.g., America/New_York)', max_length=50)),
                ('location', models.CharField(blank=True, help_text='Physical location for on-site interviews', max_length=255)),
                ('video_link', models.URLField(blank=True, help_text='Video call link (Zoom, Google Meet, etc.)', validators=[django.core.validators.URLValidator()])),
                ('dial_in_number', models.CharField(blank=True, help_text='Phone number for dial-in option', max_length=50)),
                ('interviewer_name', models.CharField(help_text='Primary interviewer name', max_length=255)),
                ('interviewer_email', models.EmailField(help_text='Primary interviewer email', max_length=254)),
                ('additional_interviewers', models.JSONField(blank=True, default=list, help_text='List of additional interviewers: [{"name": "...", "email": "..."}]')),
                ('company_notes', models.TextField(blank=True, help_text='Internal notes for the company (not visible to candidate)')),
                ('candidate_instructions', models.TextField(blank=True, help_text='Instructions sent to the candidate')),
                ('completion_notes', models.TextField(blank=True, help_text='Notes added after interview completion')),
                ('interview_rating', models.PositiveIntegerField(blank=True, help_text='Interview rating (1-5 stars)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('interviewer_feedback', models.TextField(blank=True, help_text='Detailed feedback from interviewer')),
                ('reminder_24h_sent', models.BooleanField(default=False, help_text='Whether 24-hour reminder has been sent')),
                ('reminder_1h_sent', models.BooleanField(default=False, help_text='Whether 1-hour reminder has been sent')),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('original_scheduled_date', models.DateTimeField(blank=True, help_text='Original scheduled date before any rescheduling', null=True)),
                ('reschedule_count', models.PositiveIntegerField(default=0, help_text='Number of times this interview has been rescheduled', validators=[django.core.validators.MaxValueValidator(5)])),
                ('candidate_response', models.CharField(choices=[('PENDING', 'Pending Response'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('PROPOSED_RESCHEDULE', 'Proposed Reschedule')], default='PENDING', help_text='Candidate response to interview invitation', max_length=20)),
                ('proposed_times', models.JSONField(blank=True, default=list, help_text='Candidate-proposed alternative times: [{"date": "...", "reason": "..."}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='applications.application')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_interviews', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_interviews', to=settings.AUTH_USER_MODEL)),
                ('feedback_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews', to='interviews.interviewfeedbacktemplate')),
            ],
            options={
                'verbose_name': 'Interview',
                'verbose_name_plural': 'Interviews',
                'ordering': ['-scheduled_date'],
                'indexes': [models.Index(fields=['application', 'status'], name='interviews__applica_96ea9d_idx'), models.Index(fields=['scheduled_date'], name='interviews__schedul_c4fc43_idx'), models.Index(fields=['status', 'scheduled_date'], name='interviews__status_8cca85_idx')],
            },
        ),
    ]
