# Generated by Django 6.0.1 on 2026-01-17 14:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0004_add_source_and_cost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interview_type', models.CharField(choices=[('PHONE', 'Phone Screen'), ('VIDEO', 'Video Call'), ('ONSITE', 'On-site'), ('TECHNICAL', 'Technical Assessment'), ('BEHAVIORAL', 'Behavioral Interview')], max_length=20)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('RESCHEDULED', 'Rescheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='SCHEDULED', max_length=20)),
                ('scheduled_date', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('video_link', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('dial_in_number', models.CharField(blank=True, max_length=50)),
                ('interviewer_name', models.CharField(max_length=255)),
                ('interviewer_email', models.EmailField(max_length=254)),
                ('additional_interviewers', models.JSONField(blank=True, default=list)),
                ('company_notes', models.TextField(blank=True)),
                ('candidate_instructions', models.TextField(blank=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('reminder_24h_sent', models.BooleanField(default=False)),
                ('reminder_1h_sent', models.BooleanField(default=False)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('original_scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('reschedule_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='applications.application')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_date'],
                'indexes': [models.Index(fields=['application', 'status'], name='interviews__applica_96ea9d_idx'), models.Index(fields=['scheduled_date'], name='interviews__schedul_c4fc43_idx')],
            },
        ),
    ]
