# Generated by Django 6.0.1 on 2026-01-19 12:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_add_source_and_cost'),
        ('interviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interview',
            options={'ordering': ['-scheduled_date'], 'verbose_name': 'Interview', 'verbose_name_plural': 'Interviews'},
        ),
        migrations.RemoveField(
            model_name='interview',
            name='timezone',
        ),
        migrations.AddField(
            model_name='interview',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_interviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interview',
            name='interview_rating',
            field=models.PositiveIntegerField(blank=True, help_text='Interview rating (1-5 stars)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='interview',
            name='interviewer_feedback',
            field=models.TextField(blank=True, help_text='Detailed feedback from interviewer'),
        ),
        migrations.AddField(
            model_name='interview',
            name='timezone_name',
            field=models.CharField(default='UTC', help_text='Timezone for the scheduled date (e.g., America/New_York)', max_length=50),
        ),
        migrations.AlterField(
            model_name='interview',
            name='additional_interviewers',
            field=models.JSONField(blank=True, default=list, help_text='List of additional interviewers: [{"name": "...", "email": "..."}]'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='candidate_instructions',
            field=models.TextField(blank=True, help_text='Instructions sent to the candidate'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='company_notes',
            field=models.TextField(blank=True, help_text='Internal notes for the company (not visible to candidate)'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='completion_notes',
            field=models.TextField(blank=True, help_text='Notes added after interview completion'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='dial_in_number',
            field=models.CharField(blank=True, help_text='Phone number for dial-in option', max_length=50),
        ),
        migrations.AlterField(
            model_name='interview',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Interview duration in minutes (15-480)', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(480)]),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_type',
            field=models.CharField(choices=[('PHONE', 'Phone Screen'), ('VIDEO', 'Video Call'), ('ONSITE', 'On-site'), ('TECHNICAL', 'Technical Assessment'), ('BEHAVIORAL', 'Behavioral Interview'), ('PANEL', 'Panel Interview'), ('CULTURE_FIT', 'Culture Fit Interview'), ('FINAL', 'Final Interview')], help_text='Type of interview being conducted', max_length=20),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interviewer_email',
            field=models.EmailField(help_text='Primary interviewer email', max_length=254),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interviewer_name',
            field=models.CharField(help_text='Primary interviewer name', max_length=255),
        ),
        migrations.AlterField(
            model_name='interview',
            name='location',
            field=models.CharField(blank=True, help_text='Physical location for on-site interviews', max_length=255),
        ),
        migrations.AlterField(
            model_name='interview',
            name='original_scheduled_date',
            field=models.DateTimeField(blank=True, help_text='Original scheduled date before any rescheduling', null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='reminder_1h_sent',
            field=models.BooleanField(default=False, help_text='Whether 1-hour reminder has been sent'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='reminder_24h_sent',
            field=models.BooleanField(default=False, help_text='Whether 24-hour reminder has been sent'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='reschedule_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this interview has been rescheduled', validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='interview',
            name='scheduled_date',
            field=models.DateTimeField(help_text='Date and time of the interview'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='video_link',
            field=models.URLField(blank=True, help_text='Video call link (Zoom, Google Meet, etc.)', validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['status', 'scheduled_date'], name='interviews__status_8cca85_idx'),
        ),
    ]
