# Generated by Django 6.0.1 on 2026-01-19 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_alter_timezone_field_db_column'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='candidate_response',
            field=models.CharField(choices=[('PENDING', 'Pending Response'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('PROPOSED_RESCHEDULE', 'Proposed Reschedule')], default='PENDING', help_text='Candidate response to interview invitation', max_length=20),
        ),
        migrations.AddField(
            model_name='interview',
            name='proposed_times',
            field=models.JSONField(blank=True, default=list, help_text='Candidate-proposed alternative times: [{"date": "...", "reason": "..."}]'),
        ),
        migrations.CreateModel(
            name='InterviewFeedbackTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('interview_type', models.CharField(choices=[('PHONE', 'Phone Screen'), ('VIDEO', 'Video Call'), ('ONSITE', 'On-site'), ('TECHNICAL', 'Technical Assessment'), ('BEHAVIORAL', 'Behavioral Interview'), ('PANEL', 'Panel Interview'), ('CULTURE_FIT', 'Culture Fit Interview'), ('FINAL', 'Final Interview')], max_length=20)),
                ('questions', models.JSONField(help_text='List of questions: [{"question": "...", "type": "text|rating|boolean"}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_feedback_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AddField(
            model_name='interview',
            name='feedback_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews', to='interviews.interviewfeedbacktemplate'),
        ),
    ]
