# Generated by Django 6.0.1 on 2026-01-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_options_notification_action_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('application', 'Application'), ('message', 'Message'), ('job', 'Job'), ('system', 'System'), ('new_follower', 'New Follower')], default='system', max_length=32),
        ),
    ]
